actors:
  operandoOS:
    image_url: /images/actors/operandoOS.jpg
    name: operandoOS
    url: https://twitter.com/operandoOS
  sugaishun:
    image_url: /images/actors/sugaishun.jpg
    name: sugaishun
    url: https://twitter.com/sugaishun
  snowlong:
    image_url: /images/actors/snowlong.png
    name: snowlong
    url: https://twitter.com/_snowlong
  tetuo41:
    image_url: /images/actors/tetuo41.jpeg
    name: tetuo41
    url: https://twitter.com/tetuo41
  tsunacan:
    image_url: /images/actors/tsunacan.jpg
    name: tsunacan
  adachi:
    image_url: /images/actors/adachi.jpg
    name: adachi
  morizyun:
    image_url: /images/actors/morizyun.png
    name: morizyun
    url: https://twitter.com/zyunnosuke
  chikuwabu:
    image_url: /images/actors/chikuwabu.jpg
    name: chikuwabu
    url: https://twitter.com/_chikuwa_bu_
  yuuki:
    image_url: /images/actors/yuuki.jpg
    name: yuuki
  z_ohnami:
    image_url: /images/actors/z_ohnami.jpg
    name: z_ohnami
    url: https://twitter.com/z_ohnami
  mktakuya:
    image_url: /images/actors/mktakuya.jpg
    name: mktakuya
    url: https://twitter.com/mktakuya
  kgmyshin:
    image_url: /images/actors/kgmyshin.jpg
    name: kgmyshin
    url: https://twitter.com/kgmyshin
  umekun123:
    image_url: /images/actors/umekun123.jpg
    name: umekun123
    url: https://twitter.com/umekun123

author: tetuo41
description: Yarukinai.fmは、アラフォーのおじさんエンジニアたちと20代の若者エンジニアが雑談ベースで話すポッドキャストです。
description_long: アラフォーのおじさんエンジニアたちと20代の若者エンジニアが雑談ベースで話すポッドキャストです。
email: tetuo41@gmail.com
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics: UA-152609874-1
hashtag: yarukinaifm
itunes_podcast_url: https://podcasts.apple.com/jp/podcast/yarukinai-fm/id1468116415
spotify_podcast_url: https://open.spotify.com/show/4MY6pVYpu7bnUhWqvzVH6m
keywords: yarukinai,kinpatsu,tetuo41
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: Yarukinai.fm
url: https://yarukinai.fm
online_store: https://suzuri.jp/yarukinaifm
fanclub: https://note.com/tetuo41/circle
